<a href="https://colab.research.google.com/github/hejazn86/NLP_IMBD_reviews/blob/master/experimental_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.2.0


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
             'i love my car',
             'i love my house',
             'you love your job',
             'she loves her house',
             'She likes him'
]

tokenizer = Tokenizer(num_words = 100, oov_token='unw')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

sequences = tokenizer.texts_to_sequences(sentences)
paded_sequens = pad_sequences(sequences)

print(sequences)
print(paded_sequens)
print(word_index['she'])

{'unw': 1, 'love': 2, 'i': 3, 'my': 4, 'house': 5, 'she': 6, 'car': 7, 'you': 8, 'your': 9, 'job': 10, 'loves': 11, 'her': 12, 'likes': 13, 'him': 14}
[[3, 2, 4, 7], [3, 2, 4, 5], [8, 2, 9, 10], [6, 11, 12, 5], [6, 13, 14]]
[[ 3  2  4  7]
 [ 3  2  4  5]
 [ 8  2  9 10]
 [ 6 11 12  5]
 [ 0  6 13 14]]
6
